site_name: E7-Runa
site_url: https://mydomain.org/mysite
theme:
  name: material
  
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 


        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
  
  plugins:
    - search
    - tags

  markdown_extensions:
    - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

  nav:
    - Home: index.md
    - About: 
      - Sobre o Projeto: sobre/sobre.md
    - Documentation:
      - Documentação: documentação/Documentação.md
      - Diagramas: documentação/Diagramas.md
      - Scripts (Arquivo JavaScript): documentação/scripts.md
      - HTML: documentação/html.md

